### ISSUE TITLE
Dependent coverage over time for young adults

### ISSUE THREAD

**Issue by ougni** [gliedgroup/yam#1]
Crosstabs and temporal plots: 

1. What fraction of young adults with dependent coverage live with POIs - by year and agegroup ? 
2. What fraction of young adults with ownesi coverage live with POIs - by year and agegroup  ?

**Comment by sherryg1** [comment]
Not quite -- reverse rows and columns.  Among young adults living with POIs, what fraction have ESI coverage and what fraction have dependent coverage over time?
Among young adults not living with POIs, what fraction have ESI coverage and what fraction have dependent coverage over time?
Could put the two ESI lines (with POI, not with POI) in the same graph and look just at 19-25 year olds; likewise put the two dependent lines in the same graph

**Comment by ougni** [comment]
b61b1c13b030a5442d0bcaaac93b31d9a0b16b57
